### PR TITLE
Generate descriptions for all identifiers from UberGraph

### LINKED ISSUE #109: Add descriptions to Babel outputs for one data source
This is intended to be an initial attempt to include descriptions in NodeNorm. If we can make this work for one data source, we can extend it to others.

### PR DESCRIPTION
**Pull request by gaurav**
This PR adds code to retrieve descriptions from UberGraph and incorporate them into the compendia being generated.

It generates descriptions in the format:

```json
{
  "type": "biolink:Disease",
  "ic": "100",
  "identifiers": [{"i": "UMLS:C5235953", "l": "Locally Advanced Ewing Sarcoma"}, {"i": "NCIT:C164080", "l": "Locally Advanced Ewing Sarcoma"}],
  "descriptions": ["Ewing sarcoma that has spread from its original site of growth to nearby tissues or lymph nodes."]
}
{
  "type": "biolink:Disease",
  "ic": "100",
  "identifiers": [{"i": "MONDO:0011613", "l": "autosomal recessive early-onset Parkinson disease 6"}, {"i": "DOID:0060369", "l": "Parkinson's disease 6"}, {"i": "OMIM:605909"}, {"i": "UMLS:C1853833", "l": "Parkinson Disease 6, Autosomal Recessive Early-Onset"}, {"i": "UMLS:C1970035", "l": "PARKINSON DISEASE 6, LATE-ONSET, SUSCEPTIBILITY TO"}, {"i": "MESH:C565276", "l": "Parkinson Disease 6, Autosomal Recessive Early-Onset"}, {"i": "NCIT:C184990", "l": "Parkinson Disease 6, Early Onset"}],
  "descriptions": [
    "An autosomal recessive subtype of Parkinson disease, caused by mutation(s) in the PINK1 gene, encoding serine/threonine-protein kinase PINK1, mitochondrial.",
    "Any Parkinson disease in which the cause of the disease is a mutation in the PINK1 gene."
  ]
}
```

Closes #109

### CODE REVIEW

**Comment by gaurav** [comment]
@cbizon Done! Entries now look like this:

```json
{
  "type": "biolink:AnatomicalEntity",
  "ic": "100",
  "identifiers": [
    {
      "i": "NCIT:C98188",
      "l": "Occipital Lymph Node",
      "d": ["A lymph node located in the back of the head adjacent to the trapezius muscle."]
    }
  ]
}
```

**Review by cbizon — COMMENTED** [review]
Why is description a list?  Is there more than one per source?

**Comment by gaurav** [comment]
> Why is description a list? Is there more than one per source?

It's very rare from UberGraph, but possible: [UBERON:0001062 "anatomical entity"](http://purl.obolibrary.org/obo/UBERON_0001062) has two nearly identical description:
- `Biological entity that is either an individual member of a biological species or constitutes the structural organization of an individual member of a biological species.`
- `Biological entity that is either an individual member of a biological species or constitutes the structural organization of an individual member of a biological species. [ FMA : 62955 http://orcid.org/0000-0001-9114-8737 ]`

In another example, one of the two descriptions is an empty string -- I've opened an issue to close that (https://github.com/TranslatorSRI/Babel/issues/154).

I was however wondering if future sources of descriptions might have multiple descriptions available for a particular identifier. We could come up with some rule for choosing one of them (e.g. the longer description is always selected, and a warning generated that other descriptions have been ignored), but for now it might be simplest to leave all the descriptions in and deal with this in the NodeNorm front end.

**Comment by cbizon** [comment]
Ii think it would be good to choose one if we can, but I don't think it's worth holding this up for.

**Review by cbizon — APPROVED** [review]

**Comment by gaurav** [comment]
> Ii think it would be good to choose one if we can, but I don't think it's worth holding this up for.

Fair. I've expanded https://github.com/TranslatorSRI/Babel/issues/154 to cover this.

**Pull request merged**
