### PR TITLE
Fix CURIEs used for information content

### PR DESCRIPTION
**Pull request by gaurav**
We previously used `Text.obo_to_curie()` to translate the URLs in the information content values we got back from UberGraph into CURIEs. This doesn't work for complex CURIEs such as NCBIGene:4522, which is `https://identifiers.org/ncbigene/4522` (see https://github.com/TranslatorSRI/NodeNormalization/issues/182). This PR provides a warning and an immediate solution, but #226 covers a more long-term tracking option.

This PR uses the [curies](https://github.com/cthoyt/curies) package to translate URLs into CURIEs for us to use. There will still be issues (where Biolink Model and Ubergraph disagree on HTTP vs HTTPS URLs, see https://github.com/biolink/biolink-model/issues/1431), but this should help improve our information content coverage. Since this code needs `get_config()`, which set up a circular dependency, I also moved `get_config()` into node.py.

Some of these identifiers can't be mapped to CURIEs using the Biolink model -- in most cases this is because UberGraph covers concepts that we don't have in Babel (such as the Hymenoptera Anatomy Ontology), while in others it's because of slight differences in URLs, such as http-vs-https (https://github.com/biolink/biolink-model/issues/1431). Tracking and fixing this in the long term is covered by #226.

I added prefixes for a bunch of URLs to the config.json file:

```
  "ubergraph_iri_stem_to_prefix_map": {
    "https://identifiers.org/ncbigene/": "NCBIGene",
    "http://www.ncbi.nlm.nih.gov/gene/": "NCBIGene",
    "http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=": "HGNC",
    "http://www.informatics.jax.org/marker/MGI:": "MGI"
  }
```

We end up with 129,856 identifiers that can't be mapped:

```
Loaded 3637041 InformationContent values from 63 prefixes:
- NCBITaxon: 2544587
- PR: 232379
- CHEBI: 216255
- NCIT: 187148
- None: 129856
- ENSEMBL: 90375
- NCBIGene: 85209
- GO: 51304
- MONDO: 27730
- FOODON: 25348
- HGNC: 23230
- FBbt: 20110
- HP: 18049
- MGI: 16956
- UBERON: 15837
- MP: 14369
- EMAPA: 8757
- FYPO: 8250
- WBbt: 7555
- dictyBase: 4555
- ENVO: 4292
- OBI: 3979
- MA: 3257
- ZFA: 3217
- CL: 2987
- ECTO: 2887
- PATO: 2860
- WBPhenotype: 2698
- SO: 2632
- ECO: 2077
- PO: 1993
- MAXO: 1848
- TO: 1691
- MI: 1635
- FBcv: 1361
- NBO: 934
- WBls: 779
- APO: 342
- FBdv: 212
- IAO: 208
- BSPO: 140
- MPATH: 96
- PCO: 72
- CARO: 56
- ZFS: 54
- BFO: 35
- FAO: 18
- HsapDv: 12
- CLO: 6
- ExO: 6
- OGMS: 6
- RO: 5
- BTO: 3
- DDANAT: 3
- IDO: 3
- GENEPIO: 2
- SEPIO: 1
- STATO: 1
- UPHENO: 1
- XAO: 1
- schema: 1
- oboInOwl: 1
- foaf: 1
```

Here is the source summary. In this summary, I've tried to group identifiers with similar IRI stems: the number in the first column tells you how many identifiers have each IRI stem. The actual full identifiers are available in [the list of all unmapped URLs](https://github.com/TranslatorSRI/Babel/files/13936061/unmapped-urls-full.txt).

```
   1 Found 129856 unmapped URLs:
   1  - purl.obolibrary.org [76768]
 586    - http://purl.obolibrary.org/obo/AISM_
   6    - http://purl.obolibrary.org/obo/APOLLO_SV_
   1    - http://purl.obolibrary.org/obo/BCO_
  97    - http://purl.obolibrary.org/obo/BS_
   3    - http://purl.obolibrary.org/obo/CDNO_
   4    - http://purl.obolibrary.org/obo/CHMO_
 203    - http://purl.obolibrary.org/obo/CHR_
1516    - http://purl.obolibrary.org/obo/CLAO_
  74    - http://purl.obolibrary.org/obo/COB_
 214    - http://purl.obolibrary.org/obo/COLAO_
   9    - http://purl.obolibrary.org/obo/CP_
   1    - http://purl.obolibrary.org/obo/D96882F1-8709-49AB-BCA9-772A67EA6C33
   1    - http://purl.obolibrary.org/obo/DRON_
   2    - http://purl.obolibrary.org/obo/ECOCORE_
   1    - http://purl.obolibrary.org/obo/Ensembl#_BCE_
   2    - http://purl.obolibrary.org/obo/Ensembl#_BruAb1_
   2    - http://purl.obolibrary.org/obo/Ensembl#_BruAb2_
   1    - http://purl.obolibrary.org/obo/Ensembl#_HI_
   1    - http://purl.obolibrary.org/obo/Ensembl#_MG_
   9    - http://purl.obolibrary.org/obo/Ensembl#_MJ_
   7    - http://purl.obolibrary.org/obo/Ensembl#_MPN_
   2    - http://purl.obolibrary.org/obo/Ensembl#_NIES39_
   2    - http://purl.obolibrary.org/obo/Ensembl#_Nos7524_
   1    - http://purl.obolibrary.org/obo/Ensembl#_SP_
   1    - http://purl.obolibrary.org/obo/Ensembl#_SYNPCC7002_
  47    - http://purl.obolibrary.org/obo/EnsemblBacteria#_BAB1_
  23    - http://purl.obolibrary.org/obo/EnsemblBacteria#_BAB2_
  32    - http://purl.obolibrary.org/obo/EnsemblBacteria#_BCAN_
  28    - http://purl.obolibrary.org/obo/EnsemblBacteria#_BMEA_
   5    - http://purl.obolibrary.org/obo/EnsemblBacteria#_BMI_
  33    - http://purl.obolibrary.org/obo/EnsemblBacteria#_BOV_
  33    - http://purl.obolibrary.org/obo/EnsemblBacteria#_BSUIS_
  40    - http://purl.obolibrary.org/obo/EnsemblBacteria#_BruAb1_
  31    - http://purl.obolibrary.org/obo/EnsemblBacteria#_BruAb2_
   2    - http://purl.obolibrary.org/obo/EnsemblBacteria#_KOX_
  12    - http://purl.obolibrary.org/obo/EnsemblBacteria#_NWMN_
   4    - http://purl.obolibrary.org/obo/EnsemblBacteria#_SAHV_
 659    - http://purl.obolibrary.org/obo/EnsemblBacteria#_SAOUHSC_
   5    - http://purl.obolibrary.org/obo/EnsemblBacteria#_SAUSA300_
  24    - http://purl.obolibrary.org/obo/EnsemblBacteria#_SE_
   1    - http://purl.obolibrary.org/obo/EnsemblBacteria#_Saro_
   2    - http://purl.obolibrary.org/obo/EnsemblBacteria#_SaurJH1_
   1    - http://purl.obolibrary.org/obo/EnsemblBacteria#_SaurJH9_
   2    - http://purl.obolibrary.org/obo/EnsemblBacteria#_USA300HOU_
   4    - http://purl.obolibrary.org/obo/FLOPO_
  10    - http://purl.obolibrary.org/obo/GAZ_
   1    - http://purl.obolibrary.org/obo/GEO_
 913    - http://purl.obolibrary.org/obo/GNO_
  40    - http://purl.obolibrary.org/obo/GOCHE_
2596    - http://purl.obolibrary.org/obo/HAO_
 144    - http://purl.obolibrary.org/obo/LEPAO_
   6    - http://purl.obolibrary.org/obo/MFOMD_
   4    - http://purl.obolibrary.org/obo/MF_
 862    - http://purl.obolibrary.org/obo/MMO_
 109    - http://purl.obolibrary.org/obo/MOD_
   1    - http://purl.obolibrary.org/obo/MOP_
51289    - http://purl.obolibrary.org/obo/MRO_
 178    - http://purl.obolibrary.org/obo/MmusDv_
   2    - http://purl.obolibrary.org/obo/NCBITaxon#_species_
   1    - http://purl.obolibrary.org/obo/NCBITaxon#_taxonomic_
 307    - http://purl.obolibrary.org/obo/OARCS_
13364    - http://purl.obolibrary.org/obo/OBA_
  11    - http://purl.obolibrary.org/obo/OGG_
   1    - http://purl.obolibrary.org/obo/OMIABIS_
   6    - http://purl.obolibrary.org/obo/OPL_
   1    - http://purl.obolibrary.org/obo/OPMI_
2312    - http://purl.obolibrary.org/obo/PCL_
 574    - http://purl.obolibrary.org/obo/PECO_
 254    - http://purl.obolibrary.org/obo/PPO_
   2    - http://purl.obolibrary.org/obo/REO_
   1    - http://purl.obolibrary.org/obo/RnorDv_
  29    - http://purl.obolibrary.org/obo/TS_
   6    - http://purl.obolibrary.org/obo/UO_
   1    - http://purl.obolibrary.org/obo/emapa#Tmp_new_
   1    - http://purl.obolibrary.org/obo/emapa#group_
   1    - http://purl.obolibrary.org/obo/pco.owl/PCO_
   7    - https://purl.obolibrary.org/obo/PCO_
   1  - bar.utoronto.ca [16248]
16248    - https://bar.utoronto.ca/thalemine/portal.do?externalids=
   1  - rgd.mcw.edu [8198]
8198    - http://rgd.mcw.edu/rgdweb/report/gene/main.html?id=
   1  - www.yeastgenome.org [5950]
5950    - http://www.yeastgenome.org/locus/
   1  - www.pombase.org [5121]
5121    - http://www.pombase.org/spombe/result/
   1  - www.wormbase.org [4779]
4779    - http://www.wormbase.org/species/c_
   1  - flybase.org [4112]
4112    - http://flybase.org/reports/
   1  - www.ecogene.org [4042]
4042    - http://www.ecogene.org/gene/
   1  - zfin.org [3432]
3432    - http://zfin.org/action/marker/view/ZDB-GENE-
   1  - birdgenenames.org [544]
 544    - http://birdgenenames.org/cgnc/GeneReport?id=
   1  - www.ensemblgenomes.org [279]
 279    - http://www.ensemblgenomes.org/id/
   1  - www.ensembl.org [184]
 184    - http://www.ensembl.org/id/
   1  - swisslipids.org [100]
 100    - https://swisslipids.org/rdf/SLM_
   1  - www.jcvi.org [95]
   7    - http://www.jcvi.org/framework/nsf2_full_mtg#CL_
   1    - http://www.jcvi.org/framework/nsf2_full_mtg#UBERON_
  87    - http://www.jcvi.org/framework/nsf2_full_mtg#pCL_
   1  - bioregistry.io [3]
   3    - https://bioregistry.io/lipidmaps:
   1  - purl.brain-bican.org [1]
   1    - https://purl.brain-bican.org/ontology/hbao/HBA_

```

### CODE REVIEW

**Review by cbizon — CHANGES_REQUESTED** [review]
Would it make sense to solve the None issue before merging?

**Comment by gaurav** [comment]
> Would it make sense to solve the None issue before merging?

I took a stab at that: I added mappings from four IRI stems to Translator prefixes, which got us down to 129,856 unmapped URLs. I've summarized them in the PR description, although [the full list is also available](https://github.com/TranslatorSRI/Babel/files/13936061/unmapped-urls-full.txt) if you want to have a look. I compared this list to the list of prefixes in Babel from PR https://github.com/TranslatorSRI/Babel/pull/221, and I don't think we need to map any more IRI stems. What do you think?

**Review by cbizon — APPROVED** [review]
I think this is a big improvement.  The only ones that still worry me are the ensembls and model systems ids (zfin etc).  But I think that's a minor concern.

**Comment by gaurav** [comment]
Woo! Thanks, Chris!

**Pull request merged**
